export const AI_INSIGHT_MONTHLY_LIMIT = 3;
export const AI_INSIGHT_MIN_TRANSACTIONS = 4;
export const AI_INSIGHT_SMALL_TRANSACTION_THRESHOLD = 50_000;
export const AI_INSIGHT_NIGHT_START_HOUR = 20;
export const AI_INSIGHT_NIGHT_END_HOUR = 5;
